name: assignment3

on: push
jobs:
  start-time:
    runs-on: ubuntu-latest
    steps:
      - name: Set start date 
        run: echo "DATE=$date –Iminutes" >> $GITHUB_WORKFLOW_START_DATE

#      - name: Build Docker image
#        run: docker build -t yglrit/cloud-computing-homework:latest .

#  test:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2